# Generated by Django 4.2.1 on 2023-06-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_generaluser_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
