# Generated by Django 4.2.1 on 2023-06-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_alter_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
